-- =====================================================
-- Feature Updates: Voting, Online Presence, Comment Reactions
-- =====================================================

-- 1. Add upvotes/downvotes columns to tickets table
ALTER TABLE public.tickets 
  ADD COLUMN IF NOT EXISTS upvotes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS downvotes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS upvoters text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS downvoters text[] DEFAULT '{}';

-- 2. Create comment_reactions table for persistent reactions
CREATE TABLE IF NOT EXISTS public.comment_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id bigint NOT NULL REFERENCES public.ticket_comments(id) ON DELETE CASCADE,
  reaction text NOT NULL,
  user_email text NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(comment_id, reaction, user_email)
);

-- 3. Enable RLS on comment_reactions
ALTER TABLE public.comment_reactions ENABLE ROW LEVEL SECURITY;

-- 4. RLS policies for comment_reactions
CREATE POLICY "comment_reactions select" ON public.comment_reactions
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "comment_reactions insert" ON public.comment_reactions
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "comment_reactions delete" ON public.comment_reactions
  FOR DELETE USING (auth.role() = 'authenticated' AND user_email = COALESCE(auth.jwt() ->> 'email', ''));

-- 5. Add to realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE comment_reactions;

-- =====================================================
-- Run this AFTER migrate_admin_rls.sql
-- =====================================================
