-- Run this in Supabase SQL Editor if schedule saves fail with:
-- "null value in column 'id' of relation 'schedule_entries' violates not-null constraint"

ALTER TABLE public.schedule_entries
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
